/**
 *
 *  Attendance.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Attendance.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Lab1;

const std::string Attendance::Cols::_attendance_id = "\"attendance_id\"";
const std::string Attendance::Cols::_class_id = "\"class_id\"";
const std::string Attendance::Cols::_student_id = "\"student_id\"";
const std::string Attendance::Cols::_status = "\"status\"";
const std::string Attendance::primaryKeyName = "attendance_id";
const bool Attendance::hasPrimaryKey = true;
const std::string Attendance::tableName = "\"attendance\"";

const std::vector<typename Attendance::MetaData> Attendance::metaData_={
{"attendance_id","int32_t","integer",4,1,1,1},
{"class_id","int32_t","integer",4,0,0,1},
{"student_id","int32_t","integer",4,0,0,1},
{"status","std::string","character varying",20,0,0,1}
};
const std::string &Attendance::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Attendance::Attendance(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["attendance_id"].isNull())
        {
            attendanceId_=std::make_shared<int32_t>(r["attendance_id"].as<int32_t>());
        }
        if(!r["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>(r["class_id"].as<int32_t>());
        }
        if(!r["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>(r["student_id"].as<int32_t>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 4 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            attendanceId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            classId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            studentId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Attendance::Attendance(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            attendanceId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Attendance::Attendance(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("attendance_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["attendance_id"].isNull())
        {
            attendanceId_=std::make_shared<int32_t>((int32_t)pJson["attendance_id"].asInt64());
        }
    }
    if(pJson.isMember("class_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson["class_id"].asInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson["student_id"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

void Attendance::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 4)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            attendanceId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Attendance::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("attendance_id"))
    {
        if(!pJson["attendance_id"].isNull())
        {
            attendanceId_=std::make_shared<int32_t>((int32_t)pJson["attendance_id"].asInt64());
        }
    }
    if(pJson.isMember("class_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson["class_id"].asInt64());
        }
    }
    if(pJson.isMember("student_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["student_id"].isNull())
        {
            studentId_=std::make_shared<int32_t>((int32_t)pJson["student_id"].asInt64());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
}

const int32_t &Attendance::getValueOfAttendanceId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(attendanceId_)
        return *attendanceId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Attendance::getAttendanceId() const noexcept
{
    return attendanceId_;
}
void Attendance::setAttendanceId(const int32_t &pAttendanceId) noexcept
{
    attendanceId_ = std::make_shared<int32_t>(pAttendanceId);
    dirtyFlag_[0] = true;
}
const typename Attendance::PrimaryKeyType & Attendance::getPrimaryKey() const
{
    assert(attendanceId_);
    return *attendanceId_;
}

const int32_t &Attendance::getValueOfClassId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(classId_)
        return *classId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Attendance::getClassId() const noexcept
{
    return classId_;
}
void Attendance::setClassId(const int32_t &pClassId) noexcept
{
    classId_ = std::make_shared<int32_t>(pClassId);
    dirtyFlag_[1] = true;
}

const int32_t &Attendance::getValueOfStudentId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(studentId_)
        return *studentId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Attendance::getStudentId() const noexcept
{
    return studentId_;
}
void Attendance::setStudentId(const int32_t &pStudentId) noexcept
{
    studentId_ = std::make_shared<int32_t>(pStudentId);
    dirtyFlag_[2] = true;
}

const std::string &Attendance::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Attendance::getStatus() const noexcept
{
    return status_;
}
void Attendance::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[3] = true;
}
void Attendance::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[3] = true;
}

void Attendance::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Attendance::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "class_id",
        "student_id",
        "status"
    };
    return inCols;
}

void Attendance::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClassId())
        {
            binder << getValueOfClassId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Attendance::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Attendance::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClassId())
        {
            binder << getValueOfClassId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getStudentId())
        {
            binder << getValueOfStudentId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Attendance::toJson() const
{
    Json::Value ret;
    if(getAttendanceId())
    {
        ret["attendance_id"]=getValueOfAttendanceId();
    }
    else
    {
        ret["attendance_id"]=Json::Value();
    }
    if(getClassId())
    {
        ret["class_id"]=getValueOfClassId();
    }
    else
    {
        ret["class_id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

Json::Value Attendance::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 4)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getAttendanceId())
            {
                ret[pMasqueradingVector[0]]=getValueOfAttendanceId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClassId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClassId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getStudentId())
            {
                ret[pMasqueradingVector[2]]=getValueOfStudentId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[3]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getAttendanceId())
    {
        ret["attendance_id"]=getValueOfAttendanceId();
    }
    else
    {
        ret["attendance_id"]=Json::Value();
    }
    if(getClassId())
    {
        ret["class_id"]=getValueOfClassId();
    }
    else
    {
        ret["class_id"]=Json::Value();
    }
    if(getStudentId())
    {
        ret["student_id"]=getValueOfStudentId();
    }
    else
    {
        ret["student_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    return ret;
}

bool Attendance::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("attendance_id"))
    {
        if(!validJsonOfField(0, "attendance_id", pJson["attendance_id"], err, true))
            return false;
    }
    if(pJson.isMember("class_id"))
    {
        if(!validJsonOfField(1, "class_id", pJson["class_id"], err, true))
            return false;
    }
    else
    {
        err="The class_id column cannot be null";
        return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(2, "student_id", pJson["student_id"], err, true))
            return false;
    }
    else
    {
        err="The student_id column cannot be null";
        return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(3, "status", pJson["status"], err, true))
            return false;
    }
    else
    {
        err="The status column cannot be null";
        return false;
    }
    return true;
}
bool Attendance::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Attendance::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("attendance_id"))
    {
        if(!validJsonOfField(0, "attendance_id", pJson["attendance_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("class_id"))
    {
        if(!validJsonOfField(1, "class_id", pJson["class_id"], err, false))
            return false;
    }
    if(pJson.isMember("student_id"))
    {
        if(!validJsonOfField(2, "student_id", pJson["student_id"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(3, "status", pJson["status"], err, false))
            return false;
    }
    return true;
}
bool Attendance::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                  const std::vector<std::string> &pMasqueradingVector,
                                                  std::string &err)
{
    if(pMasqueradingVector.size() != 4)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Attendance::validJsonOfField(size_t index,
                                  const std::string &fieldName,
                                  const Json::Value &pJson,
                                  std::string &err,
                                  bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
