/**
 *
 *  Class.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Class.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Lab1;

const std::string Class::Cols::_class_id = "\"class_id\"";
const std::string Class::Cols::_subject_id = "\"subject_id\"";
const std::string Class::Cols::_teacher_id = "\"teacher_id\"";
const std::string Class::Cols::_class_date = "\"class_date\"";
const std::string Class::Cols::_class_type = "\"class_type\"";
const std::string Class::primaryKeyName = "class_id";
const bool Class::hasPrimaryKey = true;
const std::string Class::tableName = "\"class\"";

const std::vector<typename Class::MetaData> Class::metaData_={
{"class_id","int32_t","integer",4,1,1,1},
{"subject_id","int32_t","integer",4,0,0,1},
{"teacher_id","int32_t","integer",4,0,0,1},
{"class_date","::trantor::Date","timestamp with time zone",0,0,0,1},
{"class_type","std::string","character varying",60,0,0,1}
};
const std::string &Class::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Class::Class(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>(r["class_id"].as<int32_t>());
        }
        if(!r["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r["subject_id"].as<int32_t>());
        }
        if(!r["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>(r["teacher_id"].as<int32_t>());
        }
        if(!r["class_date"].isNull())
        {
            auto timeStr = r["class_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(r["class_type"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 5 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            classId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            teacherId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            classType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Class::Class(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            classType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

Class::Class(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("class_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson["class_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson["teacher_id"].asInt64());
        }
    }
    if(pJson.isMember("class_date"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["class_date"].isNull())
        {
            auto timeStr = pJson["class_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("class_type"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(pJson["class_type"].asString());
        }
    }
}

void Class::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 5)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[3]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            classType_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
}

void Class::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("class_id"))
    {
        if(!pJson["class_id"].isNull())
        {
            classId_=std::make_shared<int32_t>((int32_t)pJson["class_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
    if(pJson.isMember("teacher_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson["teacher_id"].asInt64());
        }
    }
    if(pJson.isMember("class_date"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["class_date"].isNull())
        {
            auto timeStr = pJson["class_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                classDate_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("class_type"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["class_type"].isNull())
        {
            classType_=std::make_shared<std::string>(pJson["class_type"].asString());
        }
    }
}

const int32_t &Class::getValueOfClassId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(classId_)
        return *classId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Class::getClassId() const noexcept
{
    return classId_;
}
void Class::setClassId(const int32_t &pClassId) noexcept
{
    classId_ = std::make_shared<int32_t>(pClassId);
    dirtyFlag_[0] = true;
}
const typename Class::PrimaryKeyType & Class::getPrimaryKey() const
{
    assert(classId_);
    return *classId_;
}

const int32_t &Class::getValueOfSubjectId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(subjectId_)
        return *subjectId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Class::getSubjectId() const noexcept
{
    return subjectId_;
}
void Class::setSubjectId(const int32_t &pSubjectId) noexcept
{
    subjectId_ = std::make_shared<int32_t>(pSubjectId);
    dirtyFlag_[1] = true;
}

const int32_t &Class::getValueOfTeacherId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(teacherId_)
        return *teacherId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Class::getTeacherId() const noexcept
{
    return teacherId_;
}
void Class::setTeacherId(const int32_t &pTeacherId) noexcept
{
    teacherId_ = std::make_shared<int32_t>(pTeacherId);
    dirtyFlag_[2] = true;
}

const ::trantor::Date &Class::getValueOfClassDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(classDate_)
        return *classDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Class::getClassDate() const noexcept
{
    return classDate_;
}
void Class::setClassDate(const ::trantor::Date &pClassDate) noexcept
{
    classDate_ = std::make_shared<::trantor::Date>(pClassDate);
    dirtyFlag_[3] = true;
}

const std::string &Class::getValueOfClassType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(classType_)
        return *classType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Class::getClassType() const noexcept
{
    return classType_;
}
void Class::setClassType(const std::string &pClassType) noexcept
{
    classType_ = std::make_shared<std::string>(pClassType);
    dirtyFlag_[4] = true;
}
void Class::setClassType(std::string &&pClassType) noexcept
{
    classType_ = std::make_shared<std::string>(std::move(pClassType));
    dirtyFlag_[4] = true;
}

void Class::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Class::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "subject_id",
        "teacher_id",
        "class_date",
        "class_type"
    };
    return inCols;
}

void Class::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSubjectId())
        {
            binder << getValueOfSubjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getClassDate())
        {
            binder << getValueOfClassDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getClassType())
        {
            binder << getValueOfClassType();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Class::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    return ret;
}

void Class::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSubjectId())
        {
            binder << getValueOfSubjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getClassDate())
        {
            binder << getValueOfClassDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getClassType())
        {
            binder << getValueOfClassType();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Class::toJson() const
{
    Json::Value ret;
    if(getClassId())
    {
        ret["class_id"]=getValueOfClassId();
    }
    else
    {
        ret["class_id"]=Json::Value();
    }
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getClassDate())
    {
        ret["class_date"]=getClassDate()->toDbStringLocal();
    }
    else
    {
        ret["class_date"]=Json::Value();
    }
    if(getClassType())
    {
        ret["class_type"]=getValueOfClassType();
    }
    else
    {
        ret["class_type"]=Json::Value();
    }
    return ret;
}

Json::Value Class::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 5)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getClassId())
            {
                ret[pMasqueradingVector[0]]=getValueOfClassId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getSubjectId())
            {
                ret[pMasqueradingVector[1]]=getValueOfSubjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getTeacherId())
            {
                ret[pMasqueradingVector[2]]=getValueOfTeacherId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getClassDate())
            {
                ret[pMasqueradingVector[3]]=getClassDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getClassType())
            {
                ret[pMasqueradingVector[4]]=getValueOfClassType();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getClassId())
    {
        ret["class_id"]=getValueOfClassId();
    }
    else
    {
        ret["class_id"]=Json::Value();
    }
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getClassDate())
    {
        ret["class_date"]=getClassDate()->toDbStringLocal();
    }
    else
    {
        ret["class_date"]=Json::Value();
    }
    if(getClassType())
    {
        ret["class_type"]=getValueOfClassType();
    }
    else
    {
        ret["class_type"]=Json::Value();
    }
    return ret;
}

bool Class::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("class_id"))
    {
        if(!validJsonOfField(0, "class_id", pJson["class_id"], err, true))
            return false;
    }
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(1, "subject_id", pJson["subject_id"], err, true))
            return false;
    }
    else
    {
        err="The subject_id column cannot be null";
        return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(2, "teacher_id", pJson["teacher_id"], err, true))
            return false;
    }
    else
    {
        err="The teacher_id column cannot be null";
        return false;
    }
    if(pJson.isMember("class_date"))
    {
        if(!validJsonOfField(3, "class_date", pJson["class_date"], err, true))
            return false;
    }
    else
    {
        err="The class_date column cannot be null";
        return false;
    }
    if(pJson.isMember("class_type"))
    {
        if(!validJsonOfField(4, "class_type", pJson["class_type"], err, true))
            return false;
    }
    else
    {
        err="The class_type column cannot be null";
        return false;
    }
    return true;
}
bool Class::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Class::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("class_id"))
    {
        if(!validJsonOfField(0, "class_id", pJson["class_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(1, "subject_id", pJson["subject_id"], err, false))
            return false;
    }
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(2, "teacher_id", pJson["teacher_id"], err, false))
            return false;
    }
    if(pJson.isMember("class_date"))
    {
        if(!validJsonOfField(3, "class_date", pJson["class_date"], err, false))
            return false;
    }
    if(pJson.isMember("class_type"))
    {
        if(!validJsonOfField(4, "class_type", pJson["class_type"], err, false))
            return false;
    }
    return true;
}
bool Class::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 5)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Class::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 60)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 60)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
