/**
 *
 *  StudentGroup.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "StudentGroup.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Lab1;

const std::string StudentGroup::Cols::_group_id = "\"group_id\"";
const std::string StudentGroup::Cols::_group_name = "\"group_name\"";
const std::string StudentGroup::Cols::_faculty = "\"faculty\"";
const std::string StudentGroup::primaryKeyName = "group_id";
const bool StudentGroup::hasPrimaryKey = true;
const std::string StudentGroup::tableName = "\"student_group\"";

const std::vector<typename StudentGroup::MetaData> StudentGroup::metaData_={
{"group_id","int32_t","integer",4,1,1,1},
{"group_name","std::string","character varying",20,0,0,1},
{"faculty","std::string","character varying",100,0,0,1}
};
const std::string &StudentGroup::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
StudentGroup::StudentGroup(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["group_id"].isNull())
        {
            groupId_=std::make_shared<int32_t>(r["group_id"].as<int32_t>());
        }
        if(!r["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(r["group_name"].as<std::string>());
        }
        if(!r["faculty"].isNull())
        {
            faculty_=std::make_shared<std::string>(r["faculty"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            groupId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            groupName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            faculty_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

StudentGroup::StudentGroup(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            faculty_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

StudentGroup::StudentGroup(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("group_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["group_id"].isNull())
        {
            groupId_=std::make_shared<int32_t>((int32_t)pJson["group_id"].asInt64());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("faculty"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["faculty"].isNull())
        {
            faculty_=std::make_shared<std::string>(pJson["faculty"].asString());
        }
    }
}

void StudentGroup::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            groupId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            faculty_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void StudentGroup::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("group_id"))
    {
        if(!pJson["group_id"].isNull())
        {
            groupId_=std::make_shared<int32_t>((int32_t)pJson["group_id"].asInt64());
        }
    }
    if(pJson.isMember("group_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["group_name"].isNull())
        {
            groupName_=std::make_shared<std::string>(pJson["group_name"].asString());
        }
    }
    if(pJson.isMember("faculty"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["faculty"].isNull())
        {
            faculty_=std::make_shared<std::string>(pJson["faculty"].asString());
        }
    }
}

const int32_t &StudentGroup::getValueOfGroupId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(groupId_)
        return *groupId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &StudentGroup::getGroupId() const noexcept
{
    return groupId_;
}
void StudentGroup::setGroupId(const int32_t &pGroupId) noexcept
{
    groupId_ = std::make_shared<int32_t>(pGroupId);
    dirtyFlag_[0] = true;
}
const typename StudentGroup::PrimaryKeyType & StudentGroup::getPrimaryKey() const
{
    assert(groupId_);
    return *groupId_;
}

const std::string &StudentGroup::getValueOfGroupName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(groupName_)
        return *groupName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StudentGroup::getGroupName() const noexcept
{
    return groupName_;
}
void StudentGroup::setGroupName(const std::string &pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(pGroupName);
    dirtyFlag_[1] = true;
}
void StudentGroup::setGroupName(std::string &&pGroupName) noexcept
{
    groupName_ = std::make_shared<std::string>(std::move(pGroupName));
    dirtyFlag_[1] = true;
}

const std::string &StudentGroup::getValueOfFaculty() const noexcept
{
    static const std::string defaultValue = std::string();
    if(faculty_)
        return *faculty_;
    return defaultValue;
}
const std::shared_ptr<std::string> &StudentGroup::getFaculty() const noexcept
{
    return faculty_;
}
void StudentGroup::setFaculty(const std::string &pFaculty) noexcept
{
    faculty_ = std::make_shared<std::string>(pFaculty);
    dirtyFlag_[2] = true;
}
void StudentGroup::setFaculty(std::string &&pFaculty) noexcept
{
    faculty_ = std::make_shared<std::string>(std::move(pFaculty));
    dirtyFlag_[2] = true;
}

void StudentGroup::updateId(const uint64_t id)
{
}

const std::vector<std::string> &StudentGroup::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "group_name",
        "faculty"
    };
    return inCols;
}

void StudentGroup::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFaculty())
        {
            binder << getValueOfFaculty();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> StudentGroup::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void StudentGroup::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getGroupName())
        {
            binder << getValueOfGroupName();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getFaculty())
        {
            binder << getValueOfFaculty();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value StudentGroup::toJson() const
{
    Json::Value ret;
    if(getGroupId())
    {
        ret["group_id"]=getValueOfGroupId();
    }
    else
    {
        ret["group_id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getFaculty())
    {
        ret["faculty"]=getValueOfFaculty();
    }
    else
    {
        ret["faculty"]=Json::Value();
    }
    return ret;
}

Json::Value StudentGroup::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getGroupId())
            {
                ret[pMasqueradingVector[0]]=getValueOfGroupId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getGroupName())
            {
                ret[pMasqueradingVector[1]]=getValueOfGroupName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getFaculty())
            {
                ret[pMasqueradingVector[2]]=getValueOfFaculty();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getGroupId())
    {
        ret["group_id"]=getValueOfGroupId();
    }
    else
    {
        ret["group_id"]=Json::Value();
    }
    if(getGroupName())
    {
        ret["group_name"]=getValueOfGroupName();
    }
    else
    {
        ret["group_name"]=Json::Value();
    }
    if(getFaculty())
    {
        ret["faculty"]=getValueOfFaculty();
    }
    else
    {
        ret["faculty"]=Json::Value();
    }
    return ret;
}

bool StudentGroup::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("group_id"))
    {
        if(!validJsonOfField(0, "group_id", pJson["group_id"], err, true))
            return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, true))
            return false;
    }
    else
    {
        err="The group_name column cannot be null";
        return false;
    }
    if(pJson.isMember("faculty"))
    {
        if(!validJsonOfField(2, "faculty", pJson["faculty"], err, true))
            return false;
    }
    else
    {
        err="The faculty column cannot be null";
        return false;
    }
    return true;
}
bool StudentGroup::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StudentGroup::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("group_id"))
    {
        if(!validJsonOfField(0, "group_id", pJson["group_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("group_name"))
    {
        if(!validJsonOfField(1, "group_name", pJson["group_name"], err, false))
            return false;
    }
    if(pJson.isMember("faculty"))
    {
        if(!validJsonOfField(2, "faculty", pJson["faculty"], err, false))
            return false;
    }
    return true;
}
bool StudentGroup::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool StudentGroup::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
