/**
 *
 *  Subject.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Subject.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Lab1;

const std::string Subject::Cols::_subject_id = "\"subject_id\"";
const std::string Subject::Cols::_subject_name = "\"subject_name\"";
const std::string Subject::primaryKeyName = "subject_id";
const bool Subject::hasPrimaryKey = true;
const std::string Subject::tableName = "\"subject\"";

const std::vector<typename Subject::MetaData> Subject::metaData_={
{"subject_id","int32_t","integer",4,1,1,1},
{"subject_name","std::string","character varying",100,0,0,1}
};
const std::string &Subject::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Subject::Subject(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r["subject_id"].as<int32_t>());
        }
        if(!r["subject_name"].isNull())
        {
            subjectName_=std::make_shared<std::string>(r["subject_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            subjectName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Subject::Subject(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

Subject::Subject(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("subject_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_name"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["subject_name"].isNull())
        {
            subjectName_=std::make_shared<std::string>(pJson["subject_name"].asString());
        }
    }
}

void Subject::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectName_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
}

void Subject::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("subject_id"))
    {
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_name"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["subject_name"].isNull())
        {
            subjectName_=std::make_shared<std::string>(pJson["subject_name"].asString());
        }
    }
}

const int32_t &Subject::getValueOfSubjectId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(subjectId_)
        return *subjectId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Subject::getSubjectId() const noexcept
{
    return subjectId_;
}
void Subject::setSubjectId(const int32_t &pSubjectId) noexcept
{
    subjectId_ = std::make_shared<int32_t>(pSubjectId);
    dirtyFlag_[0] = true;
}
const typename Subject::PrimaryKeyType & Subject::getPrimaryKey() const
{
    assert(subjectId_);
    return *subjectId_;
}

const std::string &Subject::getValueOfSubjectName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(subjectName_)
        return *subjectName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Subject::getSubjectName() const noexcept
{
    return subjectName_;
}
void Subject::setSubjectName(const std::string &pSubjectName) noexcept
{
    subjectName_ = std::make_shared<std::string>(pSubjectName);
    dirtyFlag_[1] = true;
}
void Subject::setSubjectName(std::string &&pSubjectName) noexcept
{
    subjectName_ = std::make_shared<std::string>(std::move(pSubjectName));
    dirtyFlag_[1] = true;
}

void Subject::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Subject::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "subject_name"
    };
    return inCols;
}

void Subject::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSubjectName())
        {
            binder << getValueOfSubjectName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Subject::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void Subject::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getSubjectName())
        {
            binder << getValueOfSubjectName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Subject::toJson() const
{
    Json::Value ret;
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    if(getSubjectName())
    {
        ret["subject_name"]=getValueOfSubjectName();
    }
    else
    {
        ret["subject_name"]=Json::Value();
    }
    return ret;
}

Json::Value Subject::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getSubjectId())
            {
                ret[pMasqueradingVector[0]]=getValueOfSubjectId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getSubjectName())
            {
                ret[pMasqueradingVector[1]]=getValueOfSubjectName();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    if(getSubjectName())
    {
        ret["subject_name"]=getValueOfSubjectName();
    }
    else
    {
        ret["subject_name"]=Json::Value();
    }
    return ret;
}

bool Subject::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(0, "subject_id", pJson["subject_id"], err, true))
            return false;
    }
    if(pJson.isMember("subject_name"))
    {
        if(!validJsonOfField(1, "subject_name", pJson["subject_name"], err, true))
            return false;
    }
    else
    {
        err="The subject_name column cannot be null";
        return false;
    }
    return true;
}
bool Subject::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Subject::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(0, "subject_id", pJson["subject_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("subject_name"))
    {
        if(!validJsonOfField(1, "subject_name", pJson["subject_name"], err, false))
            return false;
    }
    return true;
}
bool Subject::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Subject::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::strlen(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }

            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
