/**
 *
 *  TeacherSubject.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TeacherSubject.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::Lab1;

const std::string TeacherSubject::Cols::_teacher_id = "\"teacher_id\"";
const std::string TeacherSubject::Cols::_subject_id = "\"subject_id\"";
const std::vector<std::string> TeacherSubject::primaryKeyName = {"teacher_id","subject_id"};
const bool TeacherSubject::hasPrimaryKey = true;
const std::string TeacherSubject::tableName = "\"teacher_subject\"";

const std::vector<typename TeacherSubject::MetaData> TeacherSubject::metaData_={
{"teacher_id","int32_t","integer",4,0,1,1},
{"subject_id","int32_t","integer",4,0,1,1}
};
const std::string &TeacherSubject::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TeacherSubject::TeacherSubject(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>(r["teacher_id"].as<int32_t>());
        }
        if(!r["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r["subject_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 2 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            teacherId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            subjectId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

TeacherSubject::TeacherSubject(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

TeacherSubject::TeacherSubject(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("teacher_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson["teacher_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
}

void TeacherSubject::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 2)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
}

void TeacherSubject::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("teacher_id"))
    {
        if(!pJson["teacher_id"].isNull())
        {
            teacherId_=std::make_shared<int32_t>((int32_t)pJson["teacher_id"].asInt64());
        }
    }
    if(pJson.isMember("subject_id"))
    {
        if(!pJson["subject_id"].isNull())
        {
            subjectId_=std::make_shared<int32_t>((int32_t)pJson["subject_id"].asInt64());
        }
    }
}

const int32_t &TeacherSubject::getValueOfTeacherId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(teacherId_)
        return *teacherId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TeacherSubject::getTeacherId() const noexcept
{
    return teacherId_;
}
void TeacherSubject::setTeacherId(const int32_t &pTeacherId) noexcept
{
    teacherId_ = std::make_shared<int32_t>(pTeacherId);
    dirtyFlag_[0] = true;
}

const int32_t &TeacherSubject::getValueOfSubjectId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(subjectId_)
        return *subjectId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TeacherSubject::getSubjectId() const noexcept
{
    return subjectId_;
}
void TeacherSubject::setSubjectId(const int32_t &pSubjectId) noexcept
{
    subjectId_ = std::make_shared<int32_t>(pSubjectId);
    dirtyFlag_[1] = true;
}

void TeacherSubject::updateId(const uint64_t id)
{
}
typename TeacherSubject::PrimaryKeyType TeacherSubject::getPrimaryKey() const
{
    return std::make_tuple(*teacherId_,*subjectId_);
}

const std::vector<std::string> &TeacherSubject::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "teacher_id",
        "subject_id"
    };
    return inCols;
}

void TeacherSubject::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getSubjectId())
        {
            binder << getValueOfSubjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TeacherSubject::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    return ret;
}

void TeacherSubject::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeacherId())
        {
            binder << getValueOfTeacherId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getSubjectId())
        {
            binder << getValueOfSubjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TeacherSubject::toJson() const
{
    Json::Value ret;
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    return ret;
}

Json::Value TeacherSubject::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 2)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getTeacherId())
            {
                ret[pMasqueradingVector[0]]=getValueOfTeacherId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getSubjectId())
            {
                ret[pMasqueradingVector[1]]=getValueOfSubjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getTeacherId())
    {
        ret["teacher_id"]=getValueOfTeacherId();
    }
    else
    {
        ret["teacher_id"]=Json::Value();
    }
    if(getSubjectId())
    {
        ret["subject_id"]=getValueOfSubjectId();
    }
    else
    {
        ret["subject_id"]=Json::Value();
    }
    return ret;
}

bool TeacherSubject::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(0, "teacher_id", pJson["teacher_id"], err, true))
            return false;
    }
    else
    {
        err="The teacher_id column cannot be null";
        return false;
    }
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(1, "subject_id", pJson["subject_id"], err, true))
            return false;
    }
    else
    {
        err="The subject_id column cannot be null";
        return false;
    }
    return true;
}
bool TeacherSubject::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TeacherSubject::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("teacher_id"))
    {
        if(!validJsonOfField(0, "teacher_id", pJson["teacher_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("subject_id"))
    {
        if(!validJsonOfField(1, "subject_id", pJson["subject_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    return true;
}
bool TeacherSubject::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 2)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TeacherSubject::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
